openapi: 3.0.1
info:
  title: 우리집 레시피 API Documentation
  description: Spring REST Docs with SwaggerUI
  version: 0.0.1
servers:
- url: http://localhost:8080/v1
tags: []
paths:
  /member/login:
    post:
      tags:
      - 회원 API
      summary: 로그인
      description: 로그인
      operationId: 로그인 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member-login-930702395'
            examples:
              로그인 API:
                value: "{\"email\":\"admin@gmail.com\",\"password\":\"Admin1234!@\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-login-1584530892'
              examples:
                로그인 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 처리되었습니다.\",\"data\":{\"\
                    accessToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzI3NTM0NTQ2LCJleHAiOjE3Mjc1MzYzNDYsInJvbGVzIjoiUk9MRV9BRE1JTiJ9.WIktJ_s07XLICoyuNs6SQScEtlk5DOLC8xotSDxoaUorvASDuhnQfgZEnFsCf9EES_yqi9UoU0qyDH65UMmW4A\"\
                    ,\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzI3NTM0NTQ2LCJleHAiOjE3Mjc2MjA5NDZ9._GzEJ0jL5kv2pwVdQ75e-9rlUHbVtGQjzKXLbpGaq30suJFF7-81LrHxajG2cUhvuU4wjO-wynOZgO_jkmfCIA\"\
                    }}"
  /member/logout:
    post:
      tags:
      - 회원 API
      summary: 로그아웃
      description: 로그아웃
      operationId: 로그아웃 API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-email-auth-request1575598845'
              examples:
                로그아웃 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 로그아웃 처리되었습니다.\"}"
      security:
      - bearerAuthJWT: []
  /member/register:
    post:
      tags:
      - 회원 API
      summary: 회원 가입
      description: 회원 가입
      operationId: 회원 가입 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member-register-1137321134'
            examples:
              회원 가입 API:
                value: "{\"email\":\"test@example.com\",\"password\":\"Pass123!@\"\
                  ,\"passwordConfirm\":\"Pass123!@\",\"nickname\":\"testUser\",\"\
                  phoneNumber\":\"010-1234-5678\",\"name\":\"테스트\",\"introduce\":\"\
                  \"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-register1233141654'
              examples:
                회원 가입 API:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":2}}"
  /member/me/profile:
    get:
      tags:
      - 회원 API
      summary: 내 프로필 조회
      description: 내 프로필 조회
      operationId: 내 프로필 조회 API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-me-profile-1720120988'
              examples:
                내 프로필 조회 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 처리되었습니다.\",\"data\":{\"\
                    id\":1,\"email\":\"admin@gmail.com\",\"nickname\":\"ê´€ë¦¬ìž\x90\
                    \ ë‹‰ë„¤ìž„\",\"phoneNumber\":\"010-000-0000\",\"name\":\"ê´€ë\
                    ¦¬ìž\x90\",\"profileImage\":\"\",\"introduce\":null}}"
      security:
      - bearerAuthJWT: []
    post:
      tags:
      - 회원 API
      summary: 내 프로필 업데이트
      description: 내 프로필 업데이트
      operationId: 내 프로필 업데이트 API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-me-profile901414125'
              examples:
                내 프로필 업데이트 API:
                  value: "{\"code\":200,\"message\":\"프로필 수정이 정상적으로 처리되었습니다.\",\"\
                    data\":{\"id\":1}}"
      security:
      - bearerAuthJWT: []
  /member/email/auth/confirm:
    post:
      tags:
      - 회원 API
      summary: 이메일 인증 코드 확인
      description: 이메일 인증 코드 확인
      operationId: 이메일 인증 코드 확인 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member-email-auth-confirm2121084288'
            examples:
              이메일 인증 코드 확인 API:
                value: "{\"email\":\"seongo0521@gmail.com\",\"authCode\":\"123456\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-email-auth-request1575598845'
              examples:
                이메일 인증 코드 확인 API:
                  value: "{\"code\":200,\"message\":\"이메일 인증이 정상적으로 처리되었습니다.\"}"
  /member/email/auth/request:
    post:
      tags:
      - 회원 API
      summary: 이메일 인증 코드 요청
      description: 이메일 인증 코드 요청
      operationId: 이메일 인증 코드 요청 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member-email-auth-request-1523986593'
            examples:
              이메일 인증 코드 요청 API:
                value: "{\"email\":\"seongo0521@gmail.com\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-email-auth-request1575598845'
              examples:
                이메일 인증 코드 요청 API:
                  value: "{\"code\":200,\"message\":\"인증 메일이 정상적으로 발송되었습니다.\"}"
components:
  schemas:
    member-login-930702395:
      type: object
      properties:
        password:
          type: string
          description: 패스워드
        email:
          type: string
          description: 이메일(아이디)
    member-email-auth-request1575598845:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        message:
          type: string
          description: 상태 메시지
    member-email-auth-request-1523986593:
      type: object
      properties:
        email:
          type: string
          description: 이메일(아이디)
    member-register1233141654:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            id:
              type: number
              description: 아이디 고유번호
        message:
          type: string
          description: 상태 메시지
    member-me-profile901414125:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            id:
              type: number
              description: 업데이트된 회원의 ID
          description: 업데이트된 프로필 데이터
        message:
          type: string
          description: 상태 메시지
    member-register-1137321134:
      type: object
      properties:
        password:
          type: string
          description: 패스워드
        phoneNumber:
          type: string
          description: 핸드폰 번호
        passwordConfirm:
          type: string
          description: 패스워드 확인
        introduce:
          type: string
          description: 소개
        name:
          type: string
          description: 이름
        nickname:
          type: string
          description: 닉네임
        email:
          type: string
          description: 이메일(아이디)
    member-login-1584530892:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          description: 토큰 데이터
        message:
          type: string
          description: 상태 메시지
    member-me-profile-1720120988:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          description: 내 프로필 데이터
        message:
          type: string
          description: 상태 메시지
    member-email-auth-confirm2121084288:
      type: object
      properties:
        authCode:
          type: string
          description: 인증 코드
        email:
          type: string
          description: 이메일(아이디)
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
