openapi: 3.0.1
info:
  title: 우리집 레시피 API Documentation
  description: Spring REST Docs with SwaggerUI
  version: 0.0.1
servers:
- url: http://localhost:8080/v1
tags: []
paths:
  /recipe/comment:
    post:
      tags:
      - 레시피 API
      summary: 레시피 댓글 등록
      description: 레시피 댓글 등록
      operationId: 레시피 댓글 등록 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/recipe-comment-88195989'
            examples:
              레시피 댓글 등록 API:
                value: "{\"recipeId\":1,\"comment\":\"댓글 테스트\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe-comment-240050280'
              examples:
                레시피 댓글 등록 API:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":1}}"
      security:
      - bearerAuthJWT: []
  /recipe/metadata:
    get:
      tags:
      - 레시피 API
      summary: 레시피 메타데이터 조회
      description: 레시피 메타데이터 조회
      operationId: 레시피 메타데이터 조회 API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe-metadata1687645871'
              examples:
                레시피 메타데이터 조회 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 처리되었습니다.\",\"data\":{\"\
                    ingredients\":[{\"ingredientId\":1,\"ingredientName\":\"ëŒ€íŒŒ\
                    \"},{\"ingredientId\":2,\"ingredientName\":\"ì²­ì–‘ê³\_ì¶”\"},{\"\
                    ingredientId\":3,\"ingredientName\":\"ìŒ€ëœ¨ë¬¼\"},{\"ingredientId\"\
                    :4,\"ingredientName\":\"ê¹€ì¹˜\"},{\"ingredientId\":5,\"ingredientName\"\
                    :\"ë\x8f¼ì§€ê³\_ê¸°\"},{\"ingredientId\":6,\"ingredientName\"\
                    :\"êµ­ê°„ìž¥\"},{\"ingredientId\":7,\"ingredientName\":\"ê³\_ì\
                    ¶§ê°€ë£¨\"},{\"ingredientId\":8,\"ingredientName\":\"ë‹¤ì§„ë§ˆ\
                    ëŠ˜\"},{\"ingredientId\":9,\"ingredientName\":\"ìƒˆìš°ì\_“\"},{\"\
                    ingredientId\":10,\"ingredientName\":\"ë\x90œìž¥\"}],\"tags\"\
                    :[{\"tagTypeName\":\"ì‹\x9dì‚¬ ì‹œê°„\",\"tags\":[{\"tagId\":1,\"\
                    tagName\":\"ì•„ì¹¨\"},{\"tagId\":2,\"tagName\":\"ì\_\x90ì‹¬\"\
                    },{\"tagId\":3,\"tagName\":\"ì\_€ë…\x81\"}]},{\"tagTypeName\"\
                    :\"ê³„ì\_ˆ\",\"tags\":[{\"tagId\":8,\"tagName\":\"ë´„\"},{\"tagId\"\
                    :9,\"tagName\":\"ì—¬ë¦„\"},{\"tagId\":10,\"tagName\":\"ê°€ì\x9d\
                    „\"},{\"tagId\":11,\"tagName\":\"ê²¨ìš¸\"}]},{\"tagTypeName\"\
                    :\"ëª©ì\_\x81\",\"tags\":[{\"tagId\":4,\"tagName\":\"ì\x9d¼ìƒ\x81\
                    \"},{\"tagId\":5,\"tagName\":\"íŒŒí‹°\"},{\"tagId\":6,\"tagName\"\
                    :\"ë‹¤ì\x9d´ì–´íŠ¸\"},{\"tagId\":7,\"tagName\":\"ì†\x90ë‹˜\"}]},{\"\
                    tagTypeName\":\"ì\x9d¸ë¶„\",\"tags\":[{\"tagId\":12,\"tagName\"\
                    :\"1ì\x9d¸ë¶„\"},{\"tagId\":13,\"tagName\":\"2ì\x9d¸ë¶„\"},{\"\
                    tagId\":14,\"tagName\":\"3ì\x9d¸ë¶„\"},{\"tagId\":15,\"tagName\"\
                    :\"4ì\x9d¸ë¶„\"},{\"tagId\":16,\"tagName\":\"ê°€ì¡±\"}]}]}}"
  /recipe/register:
    post:
      tags:
      - 레시피 API
      summary: 레시피 등록
      description: 레시피 등록
      operationId: 레시피 등록 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/recipe-register-1951027700'
            examples:
              레시피 등록 API:
                value: "{\"recipeName\":\"레시피 테스트\",\"description\":\"레시피 테스트 설명\"\
                  ,\"tags\":[{\"tagId\":12,\"tagName\":\"1인분\",\"tagTypeName\":\"인\
                  분\"}],\"ingredients\":[{\"ingredientId\":5,\"ingredientName\":\"\
                  돼지고기\",\"ingredientQuantity\":\"100\"}]}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe-register-1362881254'
              examples:
                레시피 등록 API:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":3}}"
      security:
      - bearerAuthJWT: []
  /recipe/search:
    get:
      tags:
      - 레시피 API
      summary: 레시피 이름 조회
      description: 레시피 이름 조회
      operationId: 레시피 이름 조회 API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe-search-203810791'
              examples:
                레시피 이름 조회 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 처리되었습니다.\",\"data\":{\"\
                    totalElements\":0,\"totalPages\":0,\"content\":[],\"first\":true,\"\
                    last\":true,\"sort\":{\"empty\":true,\"unsorted\":true,\"sorted\"\
                    :false},\"number\":0,\"size\":9,\"numberOfElements\":0,\"pageable\"\
                    :{\"pageNumber\":0,\"pageSize\":9,\"sort\":{\"empty\":true,\"\
                    unsorted\":true,\"sorted\":false},\"offset\":0,\"unpaged\":false,\"\
                    paged\":true},\"empty\":true}}"
  /recipe/guest/{recipeId}:
    get:
      tags:
      - 레시피 API
      summary: 레시피 상세 조회(게스트)
      description: 레시피 상세 조회(게스트)
      operationId: 레시피 상세 조회 API
      parameters:
      - name: recipeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe-comment-240050280'
              examples:
                레시피 상세 조회 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 처리되었습니다.\",\"data\":{\"\
                    recipeId\":1,\"recipeName\":\"ë\x8f¼ì§€ê³\_ê¸°\",\"recipeImage\"\
                    :\"https://our-home-recipe-bucket.s3.ap-northeast-2.amazonaws.com/no-image.jpg\"\
                    ,\"tags\":[{\"tagTypeName\":\"ì‹\x9dì‚¬ ì‹œê°„\",\"tags\":[{\"\
                    tagId\":1,\"tagName\":\"ì•„ì¹¨\"}]},{\"tagTypeName\":\"ëª©ì\_\x81\
                    \",\"tags\":[{\"tagId\":5,\"tagName\":\"íŒŒí‹°\"}]}],\"ingredients\"\
                    :[{\"ingredientId\":1,\"ingredientName\":\"ëŒ€íŒŒ\",\"ingredientQuantity\"\
                    :2.00,\"ingredientUnit\":\"ea\"},{\"ingredientId\":5,\"ingredientName\"\
                    :\"ë\x8f¼ì§€ê³\_ê¸°\",\"ingredientQuantity\":100.00,\"ingredientUnit\"\
                    :\"g\"}],\"member\":{\"memberId\":1,\"memberNickname\":\"ê´€ë¦\
                    ¬ìž\x90 ë‹‰ë„¤ìž„\",\"memberProfileImage\":\"https://our-home-recipe-bucket.s3.ap-northeast-2.amazonaws.com/no-image.jpg\"\
                    }}}"
  /recipe/member/search:
    get:
      tags:
      - 레시피 API
      summary: 레시피 회원 닉네임 조회
      description: 레시피 회원 닉네임 조회
      operationId: 레시피 회원 닉네임 조회 API
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recipe-member-search-981347922'
              examples:
                레시피 회원 닉네임 조회 API:
                  value: "{\"code\":200,\"message\":\"정상적으로 처리되었습니다.\",\"data\":{\"\
                    totalElements\":0,\"totalPages\":0,\"content\":[],\"first\":true,\"\
                    last\":true,\"sort\":{\"empty\":true,\"unsorted\":true,\"sorted\"\
                    :false},\"number\":0,\"size\":9,\"numberOfElements\":0,\"pageable\"\
                    :{\"pageNumber\":0,\"pageSize\":9,\"sort\":{\"empty\":true,\"\
                    unsorted\":true,\"sorted\":false},\"offset\":0,\"unpaged\":false,\"\
                    paged\":true},\"empty\":true}}"
components:
  schemas:
    recipe-search-203810791:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          description: "레시피 정보, 페이징 정보"
        message:
          type: string
          description: 상태 메시지
    recipe-comment-88195989:
      type: object
      properties:
        comment:
          type: string
          description: 레시피 댓글
        recipeId:
          type: number
          description: 레시피 고유 식별자
    recipe-metadata1687645871:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            ingredients:
              type: array
              description: 레시피 재료 목록
              items:
                type: object
                properties:
                  ingredientId:
                    type: number
                    description: 재료 ID
                  ingredientName:
                    type: string
                    description: 재료 이름
            tags:
              type: array
              description: 레시피 태그 목록
              items:
                type: object
                properties:
                  tagTypeName:
                    type: string
                    description: "태그 타입 이름 (예: SEASON, MEAL_TIME, SERVING, PURPOSE\
                      \ 등)"
                  tags:
                    type: array
                    description: 해당 태그 타입의 태그 목록
                    items:
                      type: object
                      properties:
                        tagId:
                          type: number
                          description: 태그 ID
                        tagName:
                          type: string
                          description: "태그 이름 (예: 봄, 여름, 아침, 점심 등)"
          description: 레시피 메타데이터
        message:
          type: string
          description: 상태 메시지
    recipe-comment-240050280:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          description: 레시피 상세 정보
        message:
          type: string
          description: 상태 메시지
    recipe-register-1951027700:
      type: object
      properties:
        recipeName:
          type: string
          description: 레시피 이름
        ingredients:
          type: array
          description: 재료 리스트
          items:
            type: object
            properties:
              ingredientId:
                type: number
                description: 재료 ID
              ingredientName:
                type: string
                description: 재료 타입
              ingredientQuantity:
                type: string
                description: 재료 수량
        description:
          type: string
          description: 레시피 설명
        tags:
          type: array
          description: 태그 리스트
          items:
            type: object
            properties:
              tagId:
                type: number
                description: 태그 ID
              tagTypeName:
                type: string
                description: 태그 타입
              tagName:
                type: string
                description: 태그 이름
    recipe-register-1362881254:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            id:
              type: number
              description: 레시피 고유번호
        message:
          type: string
          description: 상태 메시지
    recipe-member-search-981347922:
      type: object
      properties:
        code:
          type: number
          description: 상태 코드
        data:
          type: object
          properties:
            number:
              type: number
              description: 현재 페이지 번호
            numberOfElements:
              type: number
              description: 현재 페이지의 요소 수
            size:
              type: number
              description: 페이지 크기
            last:
              type: boolean
              description: 마지막 페이지 여부
            totalPages:
              type: number
              description: 총 페이지 수
            pageable:
              type: object
              properties:
                paged:
                  type: boolean
                  description: 페이징 처리 여부
                pageNumber:
                  type: number
                  description: 현재 페이지 번호
                offset:
                  type: number
                  description: 페이지 오프셋
                pageSize:
                  type: number
                  description: 페이지당 요소 수
                unpaged:
                  type: boolean
                  description: 페이징 여부
                sort:
                  type: object
                  properties:
                    unsorted:
                      type: boolean
                      description: 정렬되지 않은 상태 여부
                    sorted:
                      type: boolean
                      description: 정렬된 상태 여부
                    empty:
                      type: boolean
                      description: 정렬 정보가 비어 있는지 여부
                  description: 정렬 정보
              description: 페이징 정보
            sort:
              type: object
              properties:
                unsorted:
                  type: boolean
                  description: 정렬되지 않은 상태 여부
                sorted:
                  type: boolean
                  description: 정렬된 상태 여부
                empty:
                  type: boolean
                  description: 정렬 정보가 비어 있는지 여부
            first:
              type: boolean
              description: 첫 번째 페이지 여부
            content:
              type: array
              description: 레시피 목록
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            empty:
              type: boolean
              description: 데이터가 비어 있는지 여부
            totalElements:
              type: number
              description: 총 요소 수
          description: 레시피 회원 닉네임 조회 결과
        message:
          type: string
          description: 상태 메시지
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
