spring:
    application:
        name: api-event
    profiles:
        include: domain, infra, security
        active: local
    jpa:
        open-in-view: false # view, Controller 단에서 Lazy를 사용하지 않음
        properties:
            hibernate:
                show_sql: true # sql query console 창에 표시 여부
                format_sql: true # console 창에 보여줄때 format 여부
springdoc:
    swagger-ui:
        enabled: true

server:
    port: 8089
    servlet:
        context-path: /v1